### ISSUE TITLE
Runtime problem with _node_module_register symbol under OSX (10.1x)

### ISSUE THREAD

**Issue by dmilith** [brunch/brunch.github.io#111]
I have similar issue under OSX 10.11 and brunch (checked Node 0.10, 0.12, 4.1, 4.2).

I did standard `npm install -g brunch` which worked just fine, but in runtime it's crashing basically every time with:

```dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Projects/test2/node_modules/brunch/node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup```

This happens basically on all my boxes with osx.. I'm building Node from source in similar fasion like from brew, http://ół.pl/d066a4e2af3c3296a26155cf8f6f0662.png it works fine except that

I tried all available "solutions" that can be found online. Basically nothing helps, and Node static build isn't possible under OSX.

**Comment by dmilith** [comment]
It's worth mentioning that I had same problem under 10.10 previously. My node is built with standard options with just --prefix=/Software/NodeX - that's the main difference between "standard FHS" build done to /usr/local trash (done with brew), so don't try to look for build mistakes. There're none.

**Comment by dmilith** [comment]
To find details (for instance about how software should be built), here's my definitions - https://bitbucket.org/verknowsys/sofin-definitions/src/deb451ab3441ab3c3ad31f765ebfbbb8f3856974/definitions/node010.def?at=stable&fileviewer=file-view-default and https://bitbucket.org/verknowsys/sofin-definitions/src/deb451ab3441ab3c3ad31f765ebfbbb8f3856974/definitions/node42.def?at=stable&fileviewer=file-view-default

**Comment by dmilith** [comment]
Should I report this issue also to Node?

**Comment by dmilith** [comment]
Ok i've found a workaround. The problem cause is missing symbol: _node_module_register in binary which is stripped in normal (production) conditions. When I did build with no strip on binary, brunch built and started just fine.

**Comment by dmilith** [comment]
I checked it under FreeBSD 10/11, it works fine there after binary strip. Problem seems to be OSX (dyld) specific.

**Comment by paulmillr** [comment]
Which version of Brunch are you on? Supposing it's the latest one?
