### ISSUE TITLE
Github links to stable aren't working

### ISSUE THREAD

**Issue by aaronrenner** [brunch/brunch.github.io#119]
There are several links on your homepage pointing to Github that are returning 404s (like this one https://github.com/brunch/brunch/blob/stable/docs/README.md). I'm not sure if you want them pointing to master or a specific release, but I just wanted to let you that the links with "stable" in them aren't working.

**Comment by paulmillr** [comment]
@goshakkk

**Comment by paulmillr** [comment]
Although I suggest we don't create the "stable" branch. Let's just do releases ASAP.

**Comment by paulmillr** [comment]
updated
