### ISSUE TITLE
Create page for brunch with IDE

### ISSUE THREAD

**Issue by denar90** [brunch/brunch.github.io#137]
Hi. I propose to create new page for site with list of packages for different IDE's. 
E.g I've build some for [atom](https://github.com/denar90/brunch-with-atom)
I future someone from brunch community can build for other ide's which he/she uses and we can put the on this site page.
Is it worth?

**Comment by goshakkk** [comment]
https://github.com/brunch/brunch.github.io/pull/139 should address this :)

**Comment by goshakkk** [comment]
@paulmillr and this.
