### ISSUE TITLE
Move on https

### ISSUE THREAD

**Issue by denar90** [brunch/brunch.github.io#177]
It would be awesome if site can move on `https`.
It also will get possibility to use service workers.
I found this [article](https://blog.keanulee.com/2014/10/11/setting-up-ssl-on-github-pages.html) which might help to resolve this issue.

**Comment by paulmillr** [comment]
Not possible with GitHub. GitHub does not support SSL for custom domains.

**Comment by denar90** [comment]
Even this one is not possible to help https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/ ?
Should we roll back my pr about SW if not?
