### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by kuon** [brunch/brunch.github.io#183]
https://brunch.io is served with github SSL certificate.

this will result in a browser warning about insecure connection.

I stumbled into this because duckduckgo generates https url for brunch.io:

https://duckduckgo.com/?q=brunch+config&t=ffsb&ia=web

I think it would be good to resolve this using cloudflare for example.

**Comment by paulmillr** [comment]
Resolve how? Where do I need to put the SSL private key? We are hosting the site on GitHub.

**Comment by kuon** [comment]
You cannot resolve the issue using GitHub alone, you need to use something like [cloudflare][1] because GitHub does not support custom certificates. It's a bit cumbersome, but I think it's important for a project like brunch.

[1]: https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/

**Comment by paulmillr** [comment]
Does this mean we'll need to **buy** a SSL certificate for an OSS project; even though there are free solutions like letsencrypt? Does this also mean we'll need to pay for Cloudflare hosting?

**Comment by kuon** [comment]
No cloudflare is free and provide a free certificate.

**Comment by DoumanAsh** [comment]
@kuon What issue with Github SSL? It works just fine.

Though i would suggest to enforce HTTPs on site
http://i.imgur.com/ageiOby.png

**Comment by kuon** [comment]
If you access the site via https://brunch.io you get an invalid certificate.

**Comment by DoumanAsh** [comment]
I assume it is due to custom domain.
Certificate is perfectly valid but only for ` www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com `

**Comment by kuon** [comment]
@DoumanAsh yes, this is what I said.

**Comment by karlbateman** [comment]
Cloudflare is a great choice to resolve this issue :smile:

**Comment by filips123** [comment]
Shouldn't this issue be closed? HTTPS now works without problems.
