### ISSUE TITLE
"module.exports" vs "exports" in brunch-config.js examples

### ISSUE THREAD

**Issue by wam** [brunch/brunch.github.io#269]
Some of the `brunch-config.js` examples on the site use `module.exports` at the top level, but the default [dead-simple](https://github.com/brunch/dead-simple/blob/f3b064f829c14a1fe58bc6d063688c978ec397d1/brunch-config.js) skeleton uses plain `exports`.

For example, the [concepts page](https://github.com/brunch/brunch.github.io/blob/c60676ce2815f0d250d1e08ed69249202aac1e4d/app/assets/_docs/concepts.md) shows this as the simplest possible config:

```js
module.exports = {
  files: {
    javascripts: {joinTo: 'app.js'},
    stylesheets: {joinTo: 'app.css'}
  }
}
```

but if you run `brunch new projectname` (v2.10.9), you actually get:

```js
exports.files = {
  javascripts: {joinTo: 'app.js'},
  stylesheets: {joinTo: 'app.css'}
};
```

Should the examples on the site be brought up to date with the current output of `brunch new`? I looked through a random sample of skeletons and some of them do use `module.exports`, and both ways currently work. But `exports` at the top level seems to be the default.

I'm happy to submit a PR with changes to the relevant examples.

**Comment by denysdovhan** [comment]
Well, that's the matter of taste. Personally, I prefer to use `module.export` notation. Think about it as `export default` from ES2015, while `export.[name]` is like `export [name]`.

I agree that we need to find some consistency in our configs around the docs, but that's not the most important task we need to solve on the way to better Brunch.

**Comment by wam** [comment]
That is a very useful way of thinking about it. Thanks!

My concern was mostly that, as a newcomer to Brunch, at first I wasn't sure whether it was simply a matter of style, or if there were subtle differences in behavior, or if I'd done something wrong, or if the docs were out of date with the code.

Anyway, if you do end up wanting to change it in the docs at some point, I'd be happy to tackle that.
