### ISSUE TITLE
Problem with nav bar CSS

### ISSUE THREAD

**Issue by ngsctt** [brunch/brunch.github.io#290]
## User details
<table>
<tr>
<th>OS:</th>
<td>macOS 10.14.2 (18C54)</td>
</tr>
<tr>
<th>Browser:</th>
<td>Safari 12.0.2 (14606.3.4)</td>
</tr>
</table>

## Problem
The nav bar at the top of the docs displays incorrectly, with each page link displayed as a vertical unordered list with bullets:
<img width="1024" alt="screen shot 2018-12-17 at 01 20 26" src="https://user-images.githubusercontent.com/11954405/50054841-7a4d7a00-019a-11e9-99c3-a40f17126671.png">

## Expected behaviour
That the page links display in a single horizontal row, with the default `<ul>` styles overridden, and the text immediately below the nav bar visible.

**Comment by dlepaux** [comment]
@ngsctt Hello,
I've updated my sass-brunch PR (see above), could you confirm that all is OK now ? 
Thank you
